// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DayMonthYearTick","status":true,"description":"Allow showing quests as choice menu.","parameters":{"realLifeSecondEquivalent":"3","minuteTickCommonEvent":"1","hourTickCommonEvent":"2","dayTickCommonEvent":"3","monthTickCommonEvent":"4","yearTickCommonEvent":"0","variableForDay":"1","variableForMonth":"2","variableForYear":"3","variableForHour":"4","variableForMinute":"5","showTimeOnly":"true"}},
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"true","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}}
];
